[package]
name = "autumn_io"
version = "0.1.0"
edition = "2024"

[dependencies]
autumn-web = "0.3.0"
maud = "0.27.0"
pulldown-cmark = "0.13.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"

[dev-dependencies]
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }

[workspace]
