[package]
name = "autumn_io"
version = "0.1.0"
edition = "2024"

[dependencies]
autumn-web = { version = "0.6.0", features = ["markdown"] }
maud = "0.27.0"
pulldown-cmark = "0.13.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
syntect = { version = "5.3.0", default-features = false, features = ["default-fancy"] }
tower = "0.5"
tower-http = { version = "0.6.10", features = ["compression-gzip", "map-response-body"] }

[dev-dependencies]
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }

[workspace]
