#!/usr/bin/env bash
# Build the edge capsule and stage it for wrangler.
#
# This is what `autumn build` does for the edge step, spelled out so CI and a
# laptop run the same command:
#
#     cargo build --target wasm32-wasip1 --release --bin edge-capsule
#
# The `--bin` matters. This crate has several other binaries — the origin
# server, the static-site exporter, the profiling harnesses — and every one of
# them names `autumn-web`, which does not compile for wasm and is not supposed
# to. Only `edge-capsule` is an edge artifact.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
artifact="$repo_root/target/wasm32-wasip1/release/edge-capsule.wasm"
staged="$repo_root/edge/worker/build/edge-capsule.wasm"
version_module="$repo_root/edge/worker/build/capsule-version.js"

if ! rustup target list --installed | grep -qx wasm32-wasip1; then
  echo "error: the wasm32-wasip1 target is not installed." >&2
  echo "       run: rustup target add wasm32-wasip1" >&2
  exit 1
fi

echo "==> cargo build --target wasm32-wasip1 --release --bin edge-capsule"
(cd "$repo_root" && cargo build --target wasm32-wasip1 --release --bin edge-capsule)

mkdir -p "$(dirname "$staged")"
cp "$artifact" "$staged"

# The deployment version: a hash of everything that decides what the edge lane
# sends back — the capsule, the Worker sources, the security-header list and
# `wrangler.toml`. See `compute-version.sh` for why it is all four.
#
# `caches.default` in Cloudflare survives Worker deployments, so a cache entry
# keyed on the request URL alone would let a warmed colo serve the previous
# deploy's response indefinitely — and a cached 404 would hide a newly published
# guide. The Worker keys every entry on this value instead, which makes a
# deploy's entries unreachable the moment new bytes ship.
#
# Hashing the inputs rather than stamping a timestamp or a git SHA is what makes
# it exact in both directions: a rebuild that changes nothing keeps its warm
# cache, and any change that can alter a served byte invalidates it.
version=$("$repo_root/edge/compute-version.sh" "$repo_root/edge" "$staged")
cat > "$version_module" <<EOF
// Generated by edge/build-capsule.sh — do not edit.
//
// A hash of the whole response-producing bundle: the capsule, the Worker
// sources, the security-header list and wrangler.toml. Used as the colo cache
// key's version; see edge/compute-version.sh and edge/worker/src/cache.js.
export const CAPSULE_VERSION = "$version";
EOF

size=$(wc -c < "$staged")
printf '==> edge capsule: %s (%s KB), version %s\n' "$staged" "$((size / 1024))" "$version"
